name: "Cleanup packages"
description: "Cleanup packages on repository"
author: Raphael Grewe

inputs:
  arch:
    description: What architecture
    required: true
  registry:
    description: What registry
    required: true
  key:
    description: Get key
    required: true
  host:
    description: What host
    required: true

runs:
  using: "composite"
  steps:
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ env.GITHUB_TOKEN }}
    - run: |
        docker run --rm -v ${{ env.CI_PROJECT_DIR }}:/__w -e GOS_REPOSITORY_HOST="${{ inputs.host }}" -e GOS_REPOSITORY_KEY="${{ inputs.key }}" -e WORKING_DIR="/__w" --workdir /__w ${{ inputs.registry }}/${{ inputs.arch }}/repository:trixie /action.sh --clean
      shell: bash
