version: 2
updates:

- package-ecosystem: "github-actions"
  directories:
    - ".github/workflows"
    - ".github/actions/*"
  schedule:
    interval: "monthly"
  commit-message:
    prefix: "chore(deps)"
  groups:
    github-actions:
      patterns:
        - "*"
