version: 2
updates:

- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: "monthly"
  commit-message:
    prefix: "chore(deps)"
  groups:
    github-actions:
      patterns:
        - "*"

- package-ecosystem: "github-actions"
  directory: ".github/actions/autopkgtest"
  schedule:
    interval: "monthly"
  commit-message:
    prefix: "chore(deps)"
  groups:
    github-actions:
      patterns:
        - "*"

- package-ecosystem: "github-actions"
  directory: ".github/actions/blhc"
  schedule:
    interval: "monthly"
  commit-message:
    prefix: "chore(deps)"
  groups:
    github-actions:
      patterns:
        - "*"

- package-ecosystem: "github-actions"
  directory: ".github/actions/build"
  schedule:
    interval: "monthly"
  commit-message:
    prefix: "chore(deps)"
  groups:
    github-actions:
      patterns:
        - "*"

- package-ecosystem: "github-actions"
  directory: ".github/actions/clean"
  schedule:
    interval: "monthly"
  commit-message:
    prefix: "chore(deps)"
  groups:
    github-actions:
      patterns:
        - "*"

- package-ecosystem: "github-actions"
  directory: ".github/actions/clean_workspace"
  schedule:
    interval: "monthly"
  commit-message:
    prefix: "chore(deps)"
  groups:
    github-actions:
      patterns:
        - "*"

- package-ecosystem: "github-actions"
  directory: ".github/actions/lintian"
  schedule:
    interval: "monthly"
  commit-message:
    prefix: "chore(deps)"
  groups:
    github-actions:
      patterns:
        - "*"

- package-ecosystem: "github-actions"
  directory: ".github/actions/piuparts"
  schedule:
    interval: "monthly"
  commit-message:
    prefix: "chore(deps)"
  groups:
    github-actions:
      patterns:
        - "*"

- package-ecosystem: "github-actions"
  directory: ".github/actions/publish"
  schedule:
    interval: "monthly"
  commit-message:
    prefix: "chore(deps)"
  groups:
    github-actions:
      patterns:
        - "*"

- package-ecosystem: "github-actions"
  directory: ".github/actions/upload"
  schedule:
    interval: "monthly"
  commit-message:
    prefix: "chore(deps)"
  groups:
    github-actions:
      patterns:
        - "*"
