name: "Lintian test"
description: "Lintian test for Debian packages"
author: Raphael Grewe

inputs:
  arch:
    description: What architecture
    required: true
  registry:
    description: What registry
    required: true
  release:
    description: What release
    required: true

runs:
  using: "composite"
  steps:
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ env.GITHUB_TOKEN }}
    - run: |
        docker run --pull always --rm -v ${{ env.CI_PROJECT_DIR }}:/__w --workdir /__w -e WORKING_DIR="/__w/debian/output" ${{ inputs.registry }}/${{ inputs.arch }}/lintian:${{ inputs.release }}
      shell: bash
