name: "Autopkgtest test"
description: "Autopkgtest test for Debian packages"
author: Raphael Grewe

inputs:
  arch:
    description: What architecture
    required: true
  registry:
    description: What registry
    required: true
  debian_release_name:
    description: What debian release
    required: true

runs:
  using: "composite"
  steps:
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ env.GITHUB_TOKEN }}
    - run: |
        docker run --pull always --privileged --rm -v ${{ env.CI_PROJECT_DIR }}:/__w -e WORKING_DIR="/__w" --workdir /__w ${{ inputs.registry }}/${{ inputs.arch }}/autopkgtest:${{ inputs.debian_release_name }}
      shell: bash
