name: "Autopkgtest test"
description: "Autopkgtest test for Debian packages"
author: Raphael Grewe

inputs:
  arch:
    description: What architecture
    required: true
  registry:
    description: What registry
    required: true
  debian_release_name:
    description: What debian release
    required: true

runs:
  using: "composite"
  steps:
    - run: |
        # Formerly we used autopkgtest:buster docker container to run our buster lxc container.
        # Since latest upgrades on our host lxc-start is segfaulting within the buster container for unknown reason.
        # As a workaround we use the bullseye docker container instead of the buster one for all tests.
        docker run --pull always --privileged --rm -v ${{ env.CI_PROJECT_DIR }}:/__w -e WORKING_DIR="/__w" --workdir /__w ${{ inputs.registry }}/${{ inputs.arch }}/autopkgtest:bullseye
      shell: bash
